# action.yml
name: 'Buildben SQL Initial Script Generator Action'
description: 'This action is needed to build pieces of SQL code into one initialization script'
inputs:
  buildben-version:
    description: 'Buildben version for generating SQL script'
    required: true
    default: 'debug'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BUILDBEN_VERSION: ${{ inputs.buildben-version }}